# Generated by Django 2.1 on 2018-10-14 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexcard',
            old_name='icon',
            new_name='blog_link',
        ),
        migrations.AddField(
            model_name='indexcard',
            name='img_format',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexcard',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
